### PR TITLE
fix: show error details when failures==threshold

### LINKED ISSUE #634: Check failure details don't show in 'pebble checks' when failures==threshold
When the failure count is exactly the threshold, `pebble checks` doesn't provide information about the failure.

```
$ PEBBLE=/tmp go run ./cmd/pebble checks
Check  Level  Startup  Status  Failures  Change
chk1   -      enabled  up      0/3       12
$ PEBBLE=/tmp go run ./cmd/pebble checks
Check  Level  Startup  Status  Failures  Change
chk1   -      enabled  up      1/3       12 (exit status 2; ls: cannot access '/t... run "pebble tasks 12" for more)
$ PEBBLE=/tmp go run ./cmd/pebble checks
Check  Level  Startup  Status  Failures  Change
chk1   -      enabled  up      2/3       12 (exit status 2; ls: cannot access '/t... run "pebble tasks 12" for more)
$ PEBBLE=/tmp go run ./cmd/pebble checks
Check  Level  Startup  Status  Failures  Change
chk1   -      enabled  down    3/3       13
$ PEBBLE=/tmp go run ./cmd/pebble checks
Check  Level  Startup  Status  Failures  Change
chk1   -      enabled  down    4/3       13 (exit status 2; ls: cannot access '/t... run "pebble tasks 13" for more)
```

@benhoyt pointed out that it's happening because it's switched to the new change ID (13) but there are no failures on that change yet (they're still on 12).

It would be nice if we could improve this somehow.

### PR DESCRIPTION
**Pull request by tonyandrewmeyer**
This PR enhances health check observability by tracking the previous change associated with a check, propagating it through the daemon/client/CLI layers, and improving logging when a check’s failure threshold is reached.

Changes:

* Extend internal check tracking to include `PrevChangeID`, wire it through `CheckManager`, daemon API (`/v1/checks` and refresh), Go client, and both CLI commands (`pebble checks` and `pebble check`), and document it in the OpenAPI spec.
* Improve task logging when a check hits its failure threshold by returning an error enriched with `errorDetails(err)`, ensuring detailed output is visible in task logs.
* Update tests and helper functions to normalise / ignore dynamic change IDs (now including `prev-change-id`) where appropriate.

On the API side, the PR changes checks so that the previous change (if there is one) is included in the check data (and this included in the check/s response). On the CLI side, if there is no log data, but there is a previous change, then pull the log data from the previous change.

Previously, `pebble checks` looked like this when failures==threshold:

```
Check  Level  Startup  Status  Successes  Failures  Change
chk1   -      enabled  down    ?          3/3       2
```

And `pebble check chk1` looked like this:

```
name: chk1
startup: enabled
status: down
failures: 3
threshold: 3
change-id: "2"
```

Now `pebble checks` looks like this when failures==threshold:

```
Check  Level  Startup  Status  Successes  Failures  Change
chk1   -      enabled  down    0          3/3       44 (exit status 2; ls: cannot access '/t... run "pebble tasks 43" for more)
```

And `pebble check chk1` looks like this:

```
name: chk1
startup: enabled
status: down
successes: 0
failures: 3
threshold: 3
change-id: "44"
prev-change-id: "43"
logs: |
    2026-02-03T18:32:16+13:00 ERROR exit status 2; ls: cannot access '/tmp/veryveryveryveryveryveryverylonglonglonglonglonglongname': No such file or directory
    2026-02-03T18:32:18+13:00 ERROR exit status 2; ls: cannot access '/tmp/veryveryveryveryveryveryverylonglonglonglonglonglongname': No such file or directory
    2026-02-03T18:32:20+13:00 ERROR exit status 2; ls: cannot access '/tmp/veryveryveryveryveryveryverylonglonglonglonglonglongname': No such file or directory
```

Fixes #634

### CODE REVIEW

File: internals/overlord/checkstate/handlers.go [hunk 1]
```diff
@@ -80,8 +81,10 @@ func (m *CheckManager) doPerformCheck(task *state.Task, tomb *tombpkg.Tomb) erro
 				logger.Noticef("Check %q threshold %d hit, triggering action and recovering", config.Name, config.Threshold)
 				m.callFailureHandlers(config.Name)
 				// Returning the error means perform-check goes to Error status
-				// and logs the error to the task log.
-				return true, err
+				// and logs the error to the task log. We wrap the error to
+				// include details (such as stderr) since the task runner only
+				// logs err.Error().
+				return true, fmt.Errorf("%s", errorDetails(err))
```
Comment (benhoyt) [inline internals/overlord/checkstate/handlers.go]: You'd normally do this with `errors.New(errorDetails(err))` to avoid the %-formatting, as it's not needed here.

**Review by benhoyt — APPROVED** [review]
This looks good, thanks you.

**Comment by benhoyt** [comment]
I haven't done any manual testing, but it looks like you have. Oh, one further comment before this goes in -- it looks like the automated testing is light. It seems to me we'd need either tests in checkstate or in daemon/api_checks_test to test this new functionality internally (wherever the main tests of health checks are done now).

File: internals/overlord/checkstate/handlers.go (hunk 1 above)
Comment (tonyandrewmeyer) [reply internals/overlord/checkstate/handlers.go]:
```suggestion
				return true, errors.New(errorDetails(err))
```
