### PR TITLE
client: improve error message when pulling non-existent files

### LINKED ISSUE #722: Provide a clearer error message when pulling a non-existent file
With the Pebble snap (1.25):

```
$ pebble pull /tmp/file-does-not-exit.txt /tmp/test
error: expected first field name to be "files", got "response"
```

If it's the destination that doesn't exist, the error is nicer:

```
$ pebble pull /tmp/file.txt /tmdsfhj/sdfjhjsdf/sdfhj
error: open /tmdsfhj/sdfjhjsdf/sdfhj: no such file or directory
```

It seems like we should provide a similar error when the remote file doesn't exist.

### PR DESCRIPTION
**Pull request by Nurysso**
Fixed error message when attempting to pull a file that doesn't exist on the remote system.

Previously, when a remote file didn't exist, the Pull function would return: as mentioned in #722
```
error: expected first field name to be "files", got "response"
```

This was confusing because the API returns a "response" part (without a "files" part) when the file doesn't exist, but the client expected "files" first.

Now the client checks if the first multipart part is "response" and extracts the actual error from the API, resulting in a clearer error message:
```
error: stat /tmp/file-does-not-exist.txt: no such file or directory
```

This fix also refactors the response processing logic into a shared `processResponsePart()` helper function to eliminate code duplication between the error-first and success paths.

Fixes #722

### CODE REVIEW

File: client/files.go [hunk 1]
```diff
@@ -575,28 +575,30 @@ func (client *Client) Pull(opts *PullOptions) error {
 	if mediaType != "multipart/form-data" {
 		// If it's not multipart, it's likely an API error, so try parsing it as such.
 		var serverResp response
-		err := decodeInto(resp.Body, &serverResp)
-		if err != nil {
+		if err := decodeInto(resp.Body, &serverResp); err != nil {
```
Comment (benhoyt) [inline client/files.go]: Let's please avoid making stylistic changes like this in this PR (here and elsewhere). It makes the actual changes harder to review.

File: client/files.go [hunk 2]
```diff
@@ -606,33 +608,42 @@ func (client *Client) Pull(opts *PullOptions) error {
...
-		return fmt.Errorf(`expected second field name to be "response", got %q`, responsePart.FormName())
+		return fmt.Errorf("expected second field name to be \"response\", got %q", responsePart.FormName())
 	}
 
-	// Process response metadata (see defaultRequester.Do)
+	return processResponsePart(responsePart)
+}
+
+// processResponsePart decodes the response part and extracts any errors
+func processResponsePart(part io.Reader) error {
```
Comment (benhoyt) [inline client/files.go]: Because this is in the `client` package, let's include the word "pull" in the name. Let's call it `processPullResponsePart`.

File: client/files.go [hunk 3]
```diff
@@ -575,28 +575,30 @@ func (client *Client) Pull(opts *PullOptions) error {
...
 	}
-	defer filesPart.Close()
+	defer firstPart.Close()
 
-	if filesPart.FormName() != "files" {
-		return fmt.Errorf(`expected first field name to be "files", got %q`, filesPart.FormName())
+	// Check if we got "response" first (error case) or "files" (success case)
+	if firstPart.FormName() == "response" {
+		// Decode and process the response to extract the actual error
+		return processResponsePart(firstPart)
```
Comment (benhoyt) [inline client/files.go]: This seems reasonable. But after this `if` statement I think we should keep the `if firstPart.FormName() != "files"` block in case the field name is something other than `files` or `response`.

File: client/files.go [hunk 4]
```diff
@@ -606,33 +608,42 @@ func (client *Client) Pull(opts *PullOptions) error {
 	}
 	defer responsePart.Close()
 	if responsePart.FormName() != "response" {
-		return fmt.Errorf(`expected second field name to be "response", got %q`, responsePart.FormName())
+		return fmt.Errorf("expected second field name to be \"response\", got %q", responsePart.FormName())
```
Comment (benhoyt) [inline client/files.go]: Again, let's avoid unnecessary stylistic changes in this PR. In this case, the backticks were there for a reason, as they avoid the escaped quotes inside the string.

File: client/files.go [hunk 5]
```diff
@@ -606,33 +608,42 @@ func (client *Client) Pull(opts *PullOptions) error {
...
+	return processResponsePart(responsePart)
+}
+
+// processResponsePart decodes the response part and extracts any errors
+func processResponsePart(part io.Reader) error {
 	var multipartResp response
-	if err := decodeInto(responsePart, &multipartResp); err != nil {
-		return err
+	if err := decodeInto(part, &multipartResp); err != nil {
+		return fmt.Errorf("cannot decode response: %w", err)
```
Comment (benhoyt) [inline client/files.go]: Let's avoid this error wrapping and revert this change. `decodeInto` already adds "cannot decode ...", which I think is enough here.

File: client/files.go [hunk 6]
```diff
@@ -606,33 +608,42 @@ func (client *Client) Pull(opts *PullOptions) error {
...
 	}
+
+	// Check for error in response
 	if err := multipartResp.err(); err != nil {
 		return err
 	}
+
```
Comment (benhoyt) [inline client/files.go]: Let's avoid the additional line breaks here and below. These code sections were nicely divided into "paragraphs" already -- it's less clear to have each if statement as its own "paragraph".

**Review by benhoyt — CHANGES_REQUESTED** [review]
Thanks. Left some comments: mostly minor stylistic changes.

In addition, we should add a test of this code path. Perhaps you can do something similar to `TestPullFailsWithErrorResponse`, added [here](https://github.com/canonical/pebble/pull/452/files#diff-411ef57155896d34b3c3bfbfe080e0ab13e4cd0242359972d282583d0e2daf65).

File: client/files.go (hunk 6 above)
Comment (Nurysso) [reply client/files.go]: okay got it will make the necessary changes

File: client/files.go [hunk 7]
```diff
@@ -609,23 +614,29 @@ func (client *Client) Pull(opts *PullOptions) error {
...
-	// Process response metadata (see defaultRequester.Do)
+	return processPullResponsePart(responsePart)
+}
+
+// processPullResponsePart decodes the response part and extracts any errors
+func processPullResponsePart(part io.Reader) error {
 	var multipartResp response
-	if err := decodeInto(responsePart, &multipartResp); err != nil {
+	if err := decodeInto(part, &multipartResp)
+	err != nil {
```
Comment (benhoyt) [inline client/files.go]: There's some funny formatting changes here, with the `err != nil {` split onto the next line (here and two places below). You can see this in the "Format" workflow failures here: https://github.com/canonical/pebble/actions/runs/20191040984/job/58022154319

File: client/files.go [hunk 8]
```diff
@@ -587,16 +587,21 @@ func (client *Client) Pull(opts *PullOptions) error {
...
-	if filesPart.FormName() != "files" {
-		return fmt.Errorf(`expected first field name to be "files", got %q`, filesPart.FormName())
+	// Check if we got "response" first (error case) or "files" (success case)
+	if firstPart.FormName() == "response" {
+		// Decode and process the response to extract the actual error
+		return processPullResponsePart(firstPart)
 	}
-	if _, err := io.Copy(opts.Target, filesPart); err != nil {
+	if firstPart.FormName() != "files" {
+		return fmt.Errorf(`expected first field name to be "files" or "response", got %q`, firstPart.FormName())
```
Comment (benhoyt) [inline client/files.go]: I'd prefer we keep this error message the same as before. Because we shouldn't really get "response" except in case of error, which is handled above.
```suggestion
		return fmt.Errorf(`expected first field name to be "files", got %q`, firstPart.FormName())
```

File: client/files.go [hunk 9]
```diff
@@ -634,5 +645,6 @@ func (client *Client) Pull(opts *PullOptions) error {
 	if fr[0].Error != nil {
 		return fr[0].Error
 	}
+
```
Comment (benhoyt) [inline client/files.go]: Nit: per earlier message, let's avoid extraneous formatting changes in this PR.

File: client/files.go (hunk 7 above)
Comment (Nurysso) [reply client/files.go]: so something like this? 
``` go
if err := decodeInto(part, &multipartResp); err != nil {
	return err
}
```

Comment (benhoyt) [reply client/files.go]: Yes, exactly. If you look at the diff here on GitHub you'll see that's what the original was.

Comment (Nurysso) [reply client/files.go]: ohh, ok everything else looks good then pushing the code

File: client/files.go (hunk 8 above)
Comment (benhoyt) [reply client/files.go]: @Nurysso You missed making this update. Committing now.

**Review by benhoyt — APPROVED** [review]

**Comment by benhoyt** [comment]
> okay so it did worked, looks like I need to improve my code formating/review skills a little more lol.

Yes, I think that would be good. :-) I always encourage my team members to do a thorough self-review using a git diff tool, or just using the GitHub diff UI itself. That would have caught a number of these follow-up issues.

> Also on a side note can i mail you sometime not regarding this project but for guidance on career/stuff i am working at?

Sure.
