### PR TITLE
fix: avoid health checks URL panic; add staticcheck

### LINKED ISSUE #579: HTTP checker fails to verify error returned by http.NewRequestWithContext
The error returned by this line is not being checked:
https://github.com/canonical/pebble/blob/65446713a1f212801a10158595b715580bac53bb/internals/overlord/checkstate/checkers.go#L54

While the most likely error scenario would be invalid URLs (which wouldn't be a problem if the caller is validating the URL beforehand), `http.NewRequestWithContext` unfortunately makes no guarantees as to when it will returns errors: https://pkg.go.dev/net/http#NewRequestWithContext

### PR DESCRIPTION
**Pull request by benhoyt**
This fixes #579, which results in a panic if an HTTP check URL was malformed. Thanks for the report and the test at https://github.com/canonical/tako/pull/24, @alnvdl-work.

I also fixed another similar "forgot to check err" issue in `cmd_warnings.go`.

This PR also adds [staticcheck](https://staticcheck.dev/) to the linting, which found this issue, and a few other minor issues. Fix the other issues and add a `staticcheck.conf` and a GitHub Action to run it. The other issues are mostly not problems, but include:

- Use of deprecated functions (these are okay, just `lint:ignore`)
- Error messages shouldn't end with "."
- `strconv.ParseFloat` second arg is not the base (10), so should be 32 or 64. I actually [tried](https://go-review.googlesource.com/c/tools/+/267600) to add this check to `go vet` years ago.
- Various unused functions and struct fields.
- `time.Now().Sub(t)` -> `time.Since(t)`
- Use of `rand.Seed` (deprecated) in tests

Fixes #579

### CODE REVIEW

File: internals/cli/cmd_help.go [hunk 1]
```diff
@@ -150,7 +146,7 @@ func (cmd cmdHelp) Execute(args []string) error {
 	}
 	if cmd.All {
 		if len(cmd.Positional.Subs) > 0 {
-			return fmt.Errorf("help accepts a command, or '--all', but not both.")
+			return fmt.Errorf("help accepts a command, or '--all', but not both")
```
Comment (alnvdl-work) [inline internals/cli/cmd_help.go:149]: So, in the other repo, this was actually deemed *not* to be a problem, so I reverted the change there. WDYT?

File: staticcheck.conf [hunk 2]
```diff
@@ -0,0 +1,6 @@
+checks = [
+	"inherit",
+	"-SA5008",  # duplicate struct tag (cli/cmd_*.go use this for "choice")
+	"-ST1012",  # error var should have name of the form errFoo
```
Comment (alnvdl-work) [inline staticcheck.conf:4]: Out of curiosity, what is the rationale for disabling this one?

File: internals/cli/cmd_help.go (hunk 1 above)
Comment (benhoyt) [reply internals/cli/cmd_help.go:149]: It's not a problem, but "error messages with the '.'" is our usual style too, and none of the other `fmt.Errorf` messages in Pebble end in a `.`, so I "fixed" it.

File: staticcheck.conf (hunk 2 above)
Comment (benhoyt) [reply staticcheck.conf]: Because these "errors" were actually not errors but sentinel values, so shouldn't really be named `errFoo`. However, I think this is a reasonable rule in general, so I ended up using line-ignores for those and re-enabling this rule in staticcheck.conf -- thanks.

**Review by IronCore864 — APPROVED** [review]
