### PR TITLE
fix: allow for the JSON overhead when reading log lines

### LINKED ISSUE #376: pebble logs fails when there is a long line (over 4k characters)
When running `pebble logs`, when there is a line with a log over 4KiB, it fails with the error (and does not show next lines):
```
$ PEBBLE_SOCKET=~/pebble/.pebble.socket go run ./cmd/pebble logs srv1
error: cannot read log line: bufio: buffer full
exit status 1
```

This is easily reproducible with a plan like this one: 
```
summary: Simple layer

description: |
    A better description for a simple layer.

services:
    srv1:
        override: replace
        summary: logs more than 4k characters
        command: bash -c "echo {1..1100}; echo "not available in logs"; sleep 10;"
        startup: enabled
```

Although long, this line size is not uncommon for a log. https://github.com/canonical/pebble/blob/95b73bb24eafa386ad4924abb57ffae9b5ef4501/client/logs.go#L30

An alternative to a bigger constant could be to print up to a fixed number of characters and skip the rest of the line.

### PR DESCRIPTION
**Pull request by tonyandrewmeyer**
The server caps lines at 4096 characters, but the client receives these as JSON, so when receiving there's an extra ~70 characters that make up the timestamp, service name, field names, and JSON punctuation. This means that limiting the slice size to 4096 characters there will result in buffer full errors.

Allow an extra 1024 characters for the JSON 'overhead' - this should be far more than needed, but is only used within the `logs` function - I wasn't able to find any maximum length for a service name, so a precise extra count is tricky. This could be lowered (I would guess 128 characters would usually be sufficient) if this might be too much memory in some Pebble use cases.

Also adds tests for the long log line cases.

Fixes #376

### CODE REVIEW

File: client/logs.go [hunk 1]
```diff
@@ -26,8 +26,10 @@ import (
 	"time"
 )
 
+// This needs to be the size of daemon.api_logs.logReaderSize, plus extra to
+// handle the timestamp, service name, and JSON syntax.
```
Comment (benhoyt) [inline client/logs.go:30]: Thanks for the explanatory comment.

Nit: in Go, the filename doesn't form part of the namespace, it's just the package name. So this would be referenced as just `daemon.logReaderSize`.

File: client/logs_test.go [hunk 2]
```diff
@@ -20,12 +20,17 @@ import (
...
 	"net/url"
+	"strings"
 
 	"gopkg.in/check.v1"
 
 	"github.com/canonical/pebble/client"
 )
 
+const (
+	maxMessageSize = 4 * 1024
```
Comment (benhoyt) [inline client/logs_test.go:31]: To reduce the scope, I'd probably put this as a local const inside the test function (that works fine in Go). Also, you can use a one-liner `const maxMessageSize = 4 * 1024`.

File: client/logs_test.go [hunk 3]
```diff
@@ -111,6 +116,38 @@ func (cs *clientSuite) TestLogsAll(c *check.C) {
...
 }
 
+func (cs *clientSuite) TestLogsLong(c *check.C) {
+	shortLog := `{"time":"2021-05-03T03:55:49.360994155Z","service":"thing","message":"log 1\n"}`
+	var longLog strings.Builder
+	longLog.WriteString(`{"time":"2021-05-03T03:55:49.460994155Z","service":"verbose","message":"`)
+	for i := 0; i < maxMessageSize; i++ {
+		longLog.WriteString("a")
+	}
+	longLog.WriteString(`\n"}`)
```
Comment (benhoyt) [inline client/logs_test.go:126]: No need for a `strings.Builder` and loop here, you can just use `strings.Repeat`:

```go
longLog := `{..., "message":"` + strings.Repeat("a", maxMessageSize) + `\n"}`
```

File: client/logs_test.go [hunk 4]
```diff
@@ -111,6 +116,38 @@ func (cs *clientSuite) TestLogsAll(c *check.C) {
...
+	logs := []string{shortLog, longLog.String(), ""}
+	cs.rsp = strings.Join(logs, "\n")
```
Comment (benhoyt) [inline client/logs_test.go:128]: I was confused at first why there was an empty string in the slice (to ensure there's a trailing newline). Would just `cs.rsp = shortLog + "\n" + longLog + "\n"` be clearer?

Could we also ensure that the next log *after* the long log comes through correctly? So maybe `shortLog + longLog + shortLog` type of thing.

File: client/logs_test.go [hunk 5]
```diff
@@ -111,6 +116,38 @@ func (cs *clientSuite) TestLogsAll(c *check.C) {
...
+		N:        -1,
+	})
+	c.Assert(err, check.IsNil)
+	c.Check(cs.req.Method, check.Equals, "GET")
+	c.Check(cs.req.URL.Path, check.Equals, "/v1/logs")
+	c.Check(cs.req.URL.Query(), check.DeepEquals, url.Values{
+		"n": []string{"-1"},
+	})
+	shortExpected := "2021-05-03T03:55:49.360Z [thing] log 1"
+	var longExpected strings.Builder
```
Comment (benhoyt) [inline client/logs_test.go:141]: Similar here as above: `strings.Repeat`

**Review by benhoyt — CHANGES_REQUESTED** [review]
Good fix and nice test structure, thanks!

I think the additional 1KB is totally fine, and a good round number that's well bigger than what any sane configuration will need. We should probably have a max length on service names, but this will do for now. We do use Pebble in "embedded Linux" contexts, but anything running a full Linux OS can handle 1KB.

**Review by benhoyt — APPROVED** [review]
Great, thanks for the fix!
