### PR TITLE
fix(servstate): reduce scope of holding ServiceManager.planLock

### LINKED ISSUE #314: Pebble is unresponsive
Some odd behaviour of Pebble was observed several times (`1.2.0` and `1.4.0` versions):

Pebble daemon starts normally and is able to spin up couple services and process several API calls. Then, quite quickly, it falls into a limbo state (thats how I understand it from the logs).

After `05 Oct 04:14:41` there are no new log entries and any CLI command execution that interacts with the daemon (e.g. `pebble changes`) simply hang.

```bash
$ sudo journalctl -feu snap.maas.pebble.service -t maas.pebble
...
Oct 05 04:14:38 maas.pebble[754145]: 2023-10-05T04:14:38.235Z [pebble] Started daemon.
Oct 05 04:14:38 maas.pebble[754145]: 2023-10-05T04:14:38.470Z [pebble] POST /v1/services 225.462757ms 202
Oct 05 04:14:38 maas.pebble[754145]: 2023-10-05T04:14:38.470Z [pebble] Started default services with change 40183.
Oct 05 04:14:38 maas.pebble[754145]: 2023-10-05T04:14:38.538Z [pebble] Service "regiond" starting: sh -c "exec systemd-cat -t maas-regiond $SNAP/bin/run-regiond"
Oct 05 04:14:39 maas.pebble[754145]: 2023-10-05T04:14:39.647Z [pebble] Service "apiserver" starting: sh -c "exec systemd-cat -t maas-apiserver $SNAP/bin/run-apiserver"
Oct 05 04:14:40 maas.pebble[754145]: 2023-10-05T04:14:40.752Z [pebble] Service "rackd" starting: sh -c "exec systemd-cat -t maas-rackd $SNAP/bin/run-rackd"
Oct 05 04:14:41 maas.pebble[754145]: 2023-10-05T04:14:41.573Z [pebble] GET /v1/services?names=bind9 120.939µs 200
Oct 05 04:14:41 maas.pebble[754145]: 2023-10-05T04:14:41.574Z [pebble] GET /v1/services?names=ntp 86.887µs 200
Oct 05 04:14:41 maas.pebble[754145]: 2023-10-05T04:14:41.574Z [pebble] GET /v1/services?names=syslog 68.915µs 200
Oct 05 04:14:41 maas.pebble[754145]: 2023-10-05T04:14:41.575Z [pebble] GET /v1/services?names=http 65.915µs 200
Oct 05 04:14:41 maas.pebble[754145]: 2023-10-05T04:14:41.576Z [pebble] GET /v1/services?names=temporal 47.774µs 200
Oct 05 04:14:41 maas.pebble[754145]: 2023-10-05T04:14:41.576Z [pebble] GET /v1/services?names=temporal 47.667µs 200
```

Sending SIGTERM doesn't help much:
```
Oct 05 14:59:47 maas.pebble[754145]: 2023-10-05T14:59:47.010Z [pebble] Exiting on interrupt signal.
```

I was unable to `strace` the daemon, however here is a `strace` of a `pebble services` call
```
[pid 1831038] 13:26:08.444799 (+     0.000015) getpeername(6, {sa_family=AF_UNIX, sun_path="/var/snap/maas/31006/pebble/.pebble.socket"}, [112->45]) = 0                                      
[pid 1831038] 13:26:08.444849 (+     0.000049) futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1) = 1                                                                                                 
[pid 1831042] 13:26:08.444879 (+     0.000030) <... futex resumed>) = 0                                                                                                                       
[pid 1831042] 13:26:08.444907 (+     0.000027) futex(0xc00008c948, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>                                                                                     
[pid 1831038] 13:26:08.444925 (+     0.000017) read(6,  <unfinished ...>                                                                                                                      
[pid 1831040] 13:26:08.444936 (+     0.000011) <... futex resumed>) = 0                                                                                                                       
[pid 1831042] 13:26:08.444947 (+     0.000010) <... futex resumed>) = 1                                                                                                                       
[pid 1831038] 13:26:08.444955 (+     0.000008) <... read resumed>0xc0001b7000, 4096) = -1 EAGAIN (Resource temporarily unavailable)                                                           
[pid 1831040] 13:26:08.444970 (+     0.000014) futex(0xc00008c948, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>                                                                               
[pid 1831038] 13:26:08.444982 (+     0.000011) futex(0xb2f228, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>                                                                                   
[pid 1831042] 13:26:08.445113 (+     0.000131) write(6, "GET /v1/services?names= HTTP/1.1"..., 108) = 108                                                                                     
[pid 1831042] 13:26:08.445189 (+     0.000076) futex(0xb2f228, FUTEX_WAKE_PRIVATE, 1) = 1                                                                                                     
[pid 1831038] 13:26:08.445221 (+     0.000031) <... futex resumed>) = 0                                                                                                                       
[pid 1831041] 13:26:08.445233 (+     0.000012) <... epoll_pwait resumed>[{EPOLLOUT, {u32=2994289048, u64=139997453302168}}], 128, 249, NULL, 0) = 1                                           
[pid 1831042] 13:26:08.445253 (+     0.000019) futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>                                                                               
[pid 1831038] 13:26:08.445264 (+     0.000011) futex(0xb2f228, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>                                                                                   
[pid 1831041] 13:26:08.445276 (+     0.000012) epoll_pwait(3, [], 128, 0, NULL, 0) = 0                                                                                                        
[pid 1831041] 13:26:08.445321 (+     0.000044) epoll_pwait(3,  <unfinished ...>
[pid 1831039] 13:26:08.445393 (+     0.000071) futex(0xb2f5e0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=248775021} <unfinished ...>
[pid 1831041] 13:26:08.693712 (+     0.248341) <... epoll_pwait resumed>[], 128, 248, NULL, 0) = 0
[pid 1831041] 13:26:08.693775 (+     0.000053) epoll_pwait(3, [], 128, 0, NULL, 0) = 0
[pid 1831041] 13:26:08.693841 (+     0.000053) epoll_pwait(3,  <unfinished ...>
[pid 1831039] 13:26:08.694339 (+     0.000503) <... futex resumed>) = -1 ETIMEDOUT (Connection timed out)
```

I don't have a stable reproducer yet and meanwhile I will try to add pprof for execution tracer.
Maybe it is related to https://github.com/canonical/pebble/issues/163

### PR DESCRIPTION
**Pull request by benhoyt**
In most cases we're just reading from m.plan fields (Services,
DefaultServiceNames, and so on), so we can use m.Plan(), which holds
the plan lock only for the duration of fetch m.plan -- this is safe,
because we never mutate what's inside m.plan, we only replace it (in
updatePlan).

This also means that in functions like Services() we're only holding
either the plan lock or the services lock at once, not both -- avoiding
the 3-way deadlock described in #314.

For the cases we are updating the plan (AppendLayer, CombineLayer,
SetServiceArgs), we still need acquirePlan.

In ServiceManager.ServiceLogs, we don't need to acquire the plan lock
at all (m.plan isn't used).

Fixes #314.

### CODE REVIEW

File: internals/daemon/daemon.go [hunk 1]
```diff
@@ -228,14 +228,11 @@ func (c *Command) Daemon() *Daemon {
...
 func (c *Command) ServeHTTP(w http.ResponseWriter, r *http.Request) {
-	st := c.d.state
-	st.Lock()
-	user, err := userFromRequest(st, r)
+	user, err := userFromRequest(nil, r) // don't pass state as this does nothing right now
 	if err != nil {
 		statusForbidden("forbidden").ServeHTTP(w, r)
 		return
 	}
-	st.Unlock()
```
Comment (benhoyt) [inline internals/daemon/daemon.go:238]: This is a drive-by for something that's not actually an issue, but seems like an accident waiting to happen -- we're not locking in the case where `userFromRequest` function returns an error. In this case doing `userFromRequest` is doing nothing, so just avoid locking altogether (can always add the lock back later as needed).

Comment (hpidcock) [reply internals/daemon/daemon.go:238]: we're not unlocking* in the case where `userFromRequest` function returns an error

**Review by hpidcock — APPROVED** [review]
Thank-you for fixing this. I'm not entirely sure how we can best avoid this in the future, but we need to be more defensive in our approach to dealing with deadlocking.

**Review by flotter — APPROVED** [review]
The explanation makes sense I could not find any issue with the implementation.
